
let lesson = [
    {
        id: 1001,
        subject: "Archery",
        location: "Dubai Sports City",
        price: 7000,
        space: 5,
        image: "images/Archery.png", 
        rating: 3,
        displaySpace: 5,
    },
    {
        id: 1002,
        subject: "Ballet",
        location: "Dubai Marina",
        price: 6000,
        space: 5,
        image: "images/Ballet.png",
        rating: 4,
        displaySpace: 5,
    },
    {
        id: 1003,
        subject: "Boxing",
        location: "Jumeirah Village Cirlce",
        price: 4000,
        space: 5,
        image: "images/boxing.png",
        rating: 4,
        displaySpace: 5,
    },
    {
        id: 1004,
        subject: "Coding and Programming",
        location: "Dubai Knowledge Village",
        price: 5000,
        space: 5,
        image: "images/Coding.png",
        rating: 5,
        displaySpace: 5,
    },
    {
        id: 1005,
        subject: "Football",
        location: "Mirdif",
        price: 4000,
        space: 5,
        image: "images/Football.png",
        rating: 5,
        displaySpace: 5,
    },
    {
        id: 1006,
        subject: "Graphic Design",
        location: "Dubai Internet City (DIC)",
        price: 5000,
        space: 5,
        image: "images/Graphic_Design.png",
        rating: 4,
        displaySpace: 5,

    },
    {
        id: 1007,
        subject: "Martial Arts",
        location: "Jumeirah",
        price: 8000,
        space: 5,
        image: "images/Martial_Arts.png",
        rating: 3,
        displaySpace: 5,
    },   
    {
        id: 1008,
        subject: "Photography",
        location: "Downtown Dubai",
        price: 3000,
        space: 5,
        image: "images/Photography.png",
        rating: 3,
        displaySpace: 5,
    },
    
    {
        id: 1009,
        subject: "Swimming",
        location: "Al Barsha",
        price: 3000,
        space: 5,
        image: "images/Swimming.png",
        rating: 4,
        displaySpace: 5,
    },
    
    {
        id: 10010,
        subject: "Yoga",
        location: "Greens",
        price: 3000,
        space: 5,
        image: "images/Yoga.png",
        rating: 5,
        displaySpace: 5,
    },
    

]